services:
  - type: web
    name: yt-backend
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg curl
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
      chmod +x /usr/local/bin/yt-dlp
      npm install
    startCommand: npm start
